version: "3"

services:
  web:
    build: .
    environment:
      - "NODE_PATH=/app/node_modules"
      - "dotenv_config_path=/data/.env"
    ports:
      - 3010:3010
    volumes:
      - ./data:/data
